# Generated by Django 6.0.4 on 2026-04-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_course_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(default='10:00', max_length=50),
        ),
    ]
