/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as LearnCourseIdRouteImport } from './routes/learn.$courseId'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminLessonsRouteImport } from './routes/admin.lessons'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin.courses.index'
import { Route as AdminCoursesNewRouteImport } from './routes/admin.courses.new'
import { Route as AdminCoursesEditCourseIdRouteImport } from './routes/admin.courses.edit.$courseId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const LearnCourseIdRoute = LearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const AdminCoursesNewRoute = AdminCoursesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const AdminCoursesEditCourseIdRoute =
  AdminCoursesEditCourseIdRouteImport.update({
    id: '/edit/$courseId',
    path: '/edit/$courseId',
    getParentRoute: () => AdminCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/courses/edit/$courseId': typeof AdminCoursesEditCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/admin/courses/edit/$courseId': typeof AdminCoursesEditCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/learn/$courseId': typeof LearnCourseIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/admin/courses/edit/$courseId': typeof AdminCoursesEditCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/courses'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/lessons'
    | '/admin/payments'
    | '/admin/students'
    | '/courses/$courseId'
    | '/learn/$courseId'
    | '/courses/'
    | '/admin/courses/new'
    | '/admin/courses/'
    | '/admin/courses/edit/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/admin/dashboard'
    | '/admin/lessons'
    | '/admin/payments'
    | '/admin/students'
    | '/courses/$courseId'
    | '/learn/$courseId'
    | '/courses'
    | '/admin/courses/new'
    | '/admin/courses'
    | '/admin/courses/edit/$courseId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/courses'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/lessons'
    | '/admin/payments'
    | '/admin/students'
    | '/courses/$courseId'
    | '/learn/$courseId'
    | '/courses/'
    | '/admin/courses/new'
    | '/admin/courses/'
    | '/admin/courses/edit/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LearnCourseIdRoute: typeof LearnCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/learn/$courseId': {
      id: '/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof LearnCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/admin/courses/new': {
      id: '/admin/courses/new'
      path: '/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminCoursesNewRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/admin/courses/edit/$courseId': {
      id: '/admin/courses/edit/$courseId'
      path: '/edit/$courseId'
      fullPath: '/admin/courses/edit/$courseId'
      preLoaderRoute: typeof AdminCoursesEditCourseIdRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
  }
}

interface AdminCoursesRouteChildren {
  AdminCoursesNewRoute: typeof AdminCoursesNewRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
  AdminCoursesEditCourseIdRoute: typeof AdminCoursesEditCourseIdRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesNewRoute: AdminCoursesNewRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
  AdminCoursesEditCourseIdRoute: AdminCoursesEditCourseIdRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminRouteChildren {
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LearnCourseIdRoute: LearnCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
